[Service]
Environment=STRIATUM_DAEMON_WEB_REPOSITORY_ID=repo_a89ecd1664764f039a127c62ab7da3f3
Environment=STRIATUM_DAEMON_WEB_TAILSCALE=1
Environment=STRIATUM_DAEMON_WEB_TAILSCALE_USERS=halbritt@gmail.com
Environment=STRIATUM_DAEMON_WEB_TAILSCALE_HOST=proximal.tail0ecc2e.ts.net
